### ISSUE TITLE
add support for post thumbnails in the widget

### ISSUE THREAD

**Issue by aschweigert** [INN/analytic-bridge#47]
removed weird largo-specific stuff in #45, but let's look into adding support for regular thumbnails in a way that would work with any theme using default wp functions, etc.

**Comment by benlk** [comment]
We should probably also add actions before and after each post, and before and after the list of posts, so that themes can add their own specific things.

**Comment by benlk** [comment]
When done with this, merge a portion of it into the RNS-specific branch.
