### ISSUE TITLE
Can't authorize plugin

### ISSUE THREAD

**Issue by ato-qi** [INN/analytic-bridge#49]
Can't finish setup – got stuck on step 3 "Connecting a Google Property View ID" 
Part of "Google Analytics Popular Posts" settings page is hidden - it shows php code: "userinfo->get(); ?>" right after comment phrase "A user with read access to your organizations Google Analytics profile must connect their Google Account."

Image here: https://yadi.sk/i/JQr8Maunu7tp5

**Comment by ato-qi** [comment]
Fixed! 
file "analytic-bridge-blog-options.php" in 348 string 
"<?" have to be changed on "<?php"

**Comment by benlk** [comment]
Yep, that does look like it would cause the bug. This might also solve #44. Thanks for the fix!

**Comment by wadehammes** [comment]
@benlk can confirm, fixing this fixed the plugin for me.
