### ISSUE TITLE
typo fix: s/Anaytic/Analytic/g; s/anaytic/analytic/g

### ISSUE THREAD

**Issue by benlk** [INN/analytic-bridge#5]
This is a really persistent typo. Everything works currently, but ick.

**Comment by benlk** [comment]
NPQ uses this typo in `inc/widgets/npq-popular-posts.php`. We're probably better off just leaving this lie.

https://bitbucket.org/projectlargo/theme-npq/src/b6891c457b935aafa384c042f1ca9c48559d67e9/inc/widgets/npq-popular-posts.php?at=master&fileviewer=file-view-default#npq-popular-posts.php-53

**Comment by aschweigert** [comment]
i think we should fix it

**Comment by benlk** [comment]
Okay. If a theme's widget has a PHP error, does the theme get disabled, or does the site just error until it gets fixed?

Will simultaneous commits in this plugin and the theme cause trouble?

**Comment by aschweigert** [comment]
We're only talking about one site so we should just update the widget on their site in parallel with this one (why do they have a custom widget in the first place?)

**Comment by benlk** [comment]
The widget in this plugin is really basic. It's just a list of posts.

The NPQ widget includes the option to show excerpts and top tags, https://bitbucket.org/projectlargo/theme-npq/src/b6891c457b935aafa384c042f1ca9c48559d67e9/inc/widgets/npq-popular-posts.php?at=master&fileviewer=file-view-default, and presents the non-excerpt-having list of posts as an `ol`, not a `ul`, though I can see a couple of bugs in the code regarding potentially-unclosed tags that aren't present in NPQ.

**Comment by aschweigert** [comment]
let's make better default widgets (in the plugin) and then replace the one in NPQ, thus also eliminating the typos.

**Comment by benlk** [comment]
Note: #26 and the commits for it did not fix the typo.
