### ISSUE TITLE
make widget output filterable

### ISSUE THREAD

**Issue by aschweigert** [INN/analytic-bridge#51]
Right now there's no easy way to modify the output of popular posts in the widget. Some sites might want to exclude a certain post type or category (sponsored content, for example) so we should probably add a filter to make it easier to do that from an individual site's theme.

**Comment by benlk** [comment]
Partially addressed in https://github.com/inn/Google-Analytics-Popular-Posts/commit/26f718a69ff10c7393578e42c8e2e24ed669adf1#diff-b7ae0382593cd8bbd542e40639bf1182 used by https://github.com/religionnews/theme-rns/blob/master/inc/widgets.php#L25-L46
