### ISSUE TITLE
No Data Showing

### ISSUE THREAD

**Issue by shootingandscuba** [INN/analytic-bridge#72]
I've setup the plugin for one site of a multi-site (network) installation as detailed on the setup guide, and I can see requests on the Google Developer side of things, but no data is showing in the plugin. All I get is "Most popular posts from Google Analytics, with a relative weighting average."

**Comment by benlk** [comment]
Hi @shootingandscuba, can you provide screenshots of what you're seeing in the plugin?

**Comment by shootingandscuba** [comment]
![ss1](https://user-images.githubusercontent.com/31658509/30104027-555823c6-92ec-11e7-9b5f-f9b36bf9b1d6.jpg)
![ss2](https://user-images.githubusercontent.com/31658509/30104031-5660f28e-92ec-11e7-8573-853b1b141508.jpg)
![ss3](https://user-images.githubusercontent.com/31658509/30104028-5560640a-92ec-11e7-9e4c-9672d83c733e.jpg)

thanks for looking into this, screenshots attached!

**Comment by benlk** [comment]
Can you save a copy of the page and send it to us, or right click upon the widget and choose "Inspect Element" and tell us if you see a `<table>` element in there? I'd like to know whether the code that's in that widget is successfully outputting the fact that it finds no popular posts, or whether it's failing to output anything at all.

https://github.com/INN/Google-Analytics-Popular-Posts/blob/07e235585149e0ee24d4b9be6a6e3516ee58f64a/classes/AnalyticsDashWidget.php#L35-L58

If you have access to your server's PHP error log, any information from there that mentions this plugin would also be of use.

**Comment by shootingandscuba** [comment]
I've added a quick line of code to analytic-bridge.php to email me the 
output of pagesql and metricsql on execution within the function 
"query_and_save_analytics"

I get the following SQL queries

PAGE

INSERT INTO `wp_analyticbridge_pages` (pagepath, post_id) VALUES
  ON DUPLICATE KEY UPDATE `id`=LAST_INSERT_ID(id)

METRIC

INSERT INTO `wp_analyticbridge_metrics`
(page_id,startdate,enddate,querytime,metric,value) VALUES
  ON DUPLICATE KEY UPDATE
`id`=LAST_INSERT_ID(id),`querytime`=values(querytime),`value`=values(value)

Reading back through it looks like whatever code runs the condition for 
generating the value array for each insert is not being met.


Duncan

**Comment by benlk** [comment]
Could you log the content of `$report->rows` sometime after the report is fetched from GA, after these lines https://github.com/INN/Google-Analytics-Popular-Posts/blob/d3a5ffccec1902fe158e7f69ba4f708f49e15fdd/analytic-bridge.php#L153-L163 but before the `try ... catch` statement?

**Comment by shootingandscuba** [comment]
a var_dump of the $report->rows before the try / catch returns empty

**Comment by benlk** [comment]
What about `var_dump`ing all of $report? 

That `$report->rows` is empty suggests that something is wrong in the Google Analytics integration. Does your Google Analytics dashboard show any page views?
