### ISSUE TITLE
wp_query to make loop to return results to custom template

### ISSUE THREAD

**Issue by newvision2112** [INN/analytic-bridge#75]
Hello, 

Your plugin looks useful. However I've run into a couple issues. 

1. I have a custom coded theme so can't use the widget. Can you share basic PHP code for a WP_query to test pulling back data from the database tables? Then I can test writing a list of popular posts to my templates.

2. When installed and updated, it looks like the database tables are empty(?). I've verified that I'm pulling in data and connected to my GA account. If I can create a query then I can test this.

Thanks,
Dean

**Comment by benlk** [comment]
Hi Dean,

We strongly recommend [registering a sidebar](https://codex.wordpress.org/Sidebars) in your custom theme, outputting the sidebar on the page, and then putting the widget in your sidebar. Failing that, you can use the WordPress template tag function [`the_widget`](https://developer.wordpress.org/reference/functions/the_widget/) to output the widget, but we've never attempted that with this plugin and cannot guarantee whether it will work. Sample code for querying the data can be found in the widget included in this plugin, at https://github.com/INN/Google-Analytics-Popular-Posts/blob/master/classes/AnalyticsPopularWidget.php#L44-L165

If the database tables are indeed empty, and are not updating, please see if you can reproduce the issue described in https://github.com/INN/Google-Analytics-Popular-Posts/issues/72

**Comment by newvision2112** [comment]
Hi Ben,

Thank you for the detailed suggestions. I will test now.

Appreciate it,
Dean

**Comment by newvision2112** [comment]
Hi Ben,

Got it working! Thank you.

Q: Can I change the timeframe to 30 days? So most popular posts based on
Google Analytics for last 30 days?

Best,
Dean

**Comment by benlk** [comment]
Not easily. You'd need to completely rewrite `AnalyticBridgePopularPosts::query()` to grab posts from more than the last two days https://github.com/INN/Google-Analytics-Popular-Posts/blob/7378ac73f924b438c0ab6c0f04cd521a23725117/classes/AnalyticBridgePopularPosts.php#L35-L148

And you'd see a massive performance hit on your site when running that query.

**Comment by newvision2112** [comment]
Hi Ben,

Thanks for explaining the weighted part and the need to re-write the query.

It would be useful to just ask Google for top posts for last 30 days and have them do the heavy lifting which they already do and return a list. I'll see what I can do around that.

Dean
